steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/web/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/compute-atlas/web:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/worker/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/compute-atlas/worker:latest
      - .
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/compute-atlas/web:latest
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/compute-atlas/worker:latest
substitutions:
  _REGION: us-central1

