apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: compute-atlas-web
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '3'
    spec:
      containerConcurrency: 80
      containers:
        - image: us-central1-docker.pkg.dev/YOUR_GCP_PROJECT/compute-atlas/web:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production

